# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-31 13:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('transport', '0005_vehicle_owner'),
    ]

    operations = [
        migrations.CreateModel(
            name='OfferBid',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('taken', models.BooleanField()),
                ('offer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bids', to='transport.Offer')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bidded', to='transport.SiteUser')),
            ],
        ),
    ]
