# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-31 13:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transport', '0007_offerbid_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offerbid',
            name='taken',
            field=models.BooleanField(default=False),
        ),
    ]
