# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-31 14:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transport', '0008_auto_20170531_1354'),
    ]

    operations = [
        migrations.CreateModel(
            name='Preferences',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('distance_to_start', models.FloatField(default=1)),
                ('cargo_weight', models.FloatField(default=1)),
                ('cargo_dimension', models.FloatField(default=1)),
            ],
        ),
    ]
