# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-31 14:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('transport', '0010_siteuser_preferences'),
    ]

    operations = [
        migrations.AlterField(
            model_name='siteuser',
            name='preferences',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='transport.Preferences'),
        ),
    ]
